name: "PR"

on: ["pull_request"]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v1"
        with:
          java-version: "8"
          java-package: "jdk"
          architecture: "x64"
      - name: "Build with Gradle"
        run: "./gradlew build"
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
