name: "Push Package"

on:
  push:
    branches:
      - "master"

jobs:
  push:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-java@v1"
        with:
          java-version: "8"
          java-package: "jdk"
          architecture: "x64"
      - name: "Build with Gradle"
        run: "./gradlew publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
